name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: pip install pylint black bandit

      - name: Lint - Run pylint
        run: |
          pylint bot.py
          pylint cogs
          pylint utils

      - name: Lint - Run black
        run: black --verbose --check --diff .

      - name: Lint - Run bandit
      - run: bandit -r .
